language: python
python:
    - "2.7"
install:
    - pip install -r requirements.txt pytest flake8
script:
    - py.test --config=configs/test.ini
    - "flake8 . --ignore='E124,E128,E501'"
notifications:
    email: false
    irc: "irc.freenode.org#topaz"
